// The Register 600 — first 96 entries.
//
// PRD §5.1: mid-frequency professional vocabulary. The tier you recognise on the
// page and never reach for out loud. The exclusion filter is strict — no
// ornamental SAT words. If it would sound like showing off in a standup, it is cut.
//
// Every entry carries the four fields from §5.1 plus a stress-marked respelling,
// which the read-aloud drill needs and the Lexicon may as well share:
//
//   meaning       one line, no hedging
//   collocations  the words it actually travels with — vocabulary is learned in pairs
//   slot          the room and the moment. A word with no deployment slot stays passive
//   antiPattern   the specific wrong use. Knowing the edge is most of knowing the word
//   say           respelling, not IPA. Stressed syllable in caps
//
// This file is the single source for both drills: the readings mark these words
// in their text, and the Lexicon schedules them. One authored entry, two uses.

export type Gloss = {
  word: string;
  say: string;
  meaning: string;
  collocations: string[];
  slot: string;
  antiPattern: string;
};

const ENTRIES: Gloss[] = [
  // ── Scoping, estimates, commitment ────────────────────────────────────────
  {
    word: "contingent",
    say: "kun-TIN-junt",
    meaning: "Dependent on something else happening first; not settled on its own.",
    collocations: ["contingent on", "contingent upon approval", "a contingent commitment"],
    slot: "When you are asked to commit and the honest answer has a condition attached.",
    antiPattern: "Not a synonym for 'likely'. If you cannot say contingent on *what*, use another word.",
  },
  {
    word: "tractable",
    say: "TRAK-tuh-bul",
    meaning: "Small or clear enough to actually be worked on.",
    collocations: ["make it tractable", "a tractable subset", "computationally tractable"],
    slot: "Scoping — the move from 'this is huge' to 'here is the part we can start'.",
    antiPattern: "Not 'easy'. A tractable problem can be very hard; it is merely no longer shapeless.",
  },
  {
    word: "salient",
    say: "SAY-lee-unt",
    meaning: "The detail that actually matters among many that don't.",
    collocations: ["the salient point", "the salient risk", "most salient"],
    slot: "Cutting through a long thread to the one thing that decides it.",
    antiPattern: "Salient means it stands out *from the rest*. If everything on the list matters equally, nothing is salient.",
  },
  {
    word: "marginal",
    say: "MAR-jin-ul",
    meaning: "Belonging to the next single unit — the cost or gain of one more.",
    collocations: ["marginal cost", "marginal gain", "the marginal user"],
    slot: "Arguing about scale: the tenth region does not cost what the second did.",
    antiPattern: "In business English it does not mean 'small' or 'barely relevant'. Say 'negligible' for that.",
  },
  {
    word: "precedent",
    say: "PRESS-i-dunt",
    meaning: "An earlier decision that people will now treat as the rule.",
    collocations: ["set a precedent", "there is precedent for", "without precedent"],
    slot: "Objecting to a one-off exception that will not stay one-off.",
    antiPattern: "PRESS-i-dunt, not pre-SEE-dent — that is 'precedence', which means priority.",
  },
  {
    word: "non-trivial",
    say: "non-TRIV-ee-ul",
    meaning: "Real work; more than a quick change.",
    collocations: ["non-trivial effort", "a non-trivial amount of", "non-trivially different"],
    slot: "Pushing back on a request that sounds like a two-line fix and is not.",
    antiPattern: "It is understatement, not refusal. Hiding a no inside 'non-trivial' is how people hear yes.",
  },
  {
    word: "threshold",
    say: "THRESH-hold",
    meaning: "The line at which behaviour changes.",
    collocations: ["cross a threshold", "below the threshold", "raise the threshold"],
    slot: "Turning an argument about degree into an argument about a number.",
    antiPattern: "A threshold implies something different happens on each side. A target is not a threshold.",
  },
  {
    word: "provisional",
    say: "pruh-VIZH-uh-nul",
    meaning: "Good for now, expected to be replaced.",
    collocations: ["a provisional answer", "provisional agreement", "provisionally accepted"],
    slot: "Committing to a decision while keeping the door open honestly.",
    antiPattern: "If you have no trigger for revisiting it, it is not provisional — it is permanent with a nicer label.",
  },
  {
    word: "incremental",
    say: "in-kruh-MEN-tul",
    meaning: "In steps, each one small and reversible.",
    collocations: ["incremental commitment", "incremental improvement", "incrementally"],
    slot: "Proposing a smaller first move without sounding uncommitted.",
    antiPattern: "'Only incremental' is faint praise and slightly hostile. Know which sense the room will hear.",
  },
  {
    word: "defer",
    say: "di-FUR",
    meaning: "To put off deliberately, to a named later point.",
    collocations: ["defer the decision", "defer to someone", "deferred cost"],
    slot: "Refusing to be rushed without refusing outright.",
    antiPattern: "Two senses: deferring a thing is postponing, deferring to a person is yielding. Deferring with no date is avoiding.",
  },

  // ── Failure, systems, structure ───────────────────────────────────────────
  {
    word: "proximate",
    say: "PROK-si-mut",
    meaning: "The nearest cause in the chain — what immediately preceded it.",
    collocations: ["proximate cause", "proximate trigger"],
    slot: "Opening an incident review, precisely so you can move past it.",
    antiPattern: "Not 'approximate'. Different word entirely, and a very audible slip.",
  },
  {
    word: "systemic",
    say: "sis-TEM-ik",
    meaning: "Built into how the whole thing works, not local to one incident.",
    collocations: ["systemic risk", "systemic issue", "systemic rather than individual"],
    slot: "Moving a conversation off a person and onto a structure.",
    antiPattern: "Not 'systematic', which means methodical. A systematic error is consistent; a systemic one is baked in.",
  },
  {
    word: "counterfactual",
    say: "kown-ter-FAK-choo-ul",
    meaning: "The version of events that didn't happen, used as a test.",
    collocations: ["run the counterfactual", "the counterfactual is", "counterfactual reasoning"],
    slot: "Testing whether a proposed fix would have changed anything.",
    antiPattern: "It is a tool, not a defence. 'The counterfactual is unclear' usually means you have not thought about it.",
  },
  {
    word: "mandate",
    say: "MAN-dayt",
    meaning: "An instruction issued with authority behind it.",
    collocations: ["a mandate from", "mandate a change", "without a mandate"],
    slot: "Naming the difference between a rule imposed and a practice adopted.",
    antiPattern: "Don't call a strong suggestion a mandate — the word implies someone can enforce it.",
  },
  {
    word: "latitude",
    say: "LAT-i-tewd",
    meaning: "Room to decide for yourself inside your role.",
    collocations: ["give someone latitude", "considerable latitude", "latitude to decide"],
    slot: "Asking for authority without asking for a title.",
    antiPattern: "Not freedom in general. Latitude is granted and it has edges — discretion inside a boundary.",
  },
  {
    word: "attrition",
    say: "uh-TRISH-un",
    meaning: "Steady loss over time — of people, usually, and quietly.",
    collocations: ["attrition rate", "lose people to attrition", "war of attrition"],
    slot: "Making a slow cost legible to someone who only tracks incidents.",
    antiPattern: "Layoffs are not attrition. Three good engineers leaving over eight months is.",
  },
  {
    word: "orthogonal",
    say: "or-THOG-uh-nul",
    meaning: "Independent — changing one has no bearing on the other.",
    collocations: ["orthogonal to", "keep them orthogonal", "an orthogonal concern"],
    slot: "Separating two arguments that keep getting tangled together.",
    antiPattern: "Not 'irrelevant'. Saying 'that's orthogonal' to dismiss someone is a misuse people notice.",
  },
  {
    word: "load-bearing",
    say: "LOHD-bair-ing",
    meaning: "Holding weight it doesn't look like it holds; removing it collapses something.",
    collocations: ["load-bearing dependency", "that word is load-bearing", "quietly load-bearing"],
    slot: "Flagging a component or a phrase a plan silently depends on.",
    antiPattern: "Reserve it for the non-obvious. Calling the database load-bearing says nothing.",
  },
  {
    word: "downstream",
    say: "DOWN-streem",
    meaning: "Whatever depends on this and comes after it.",
    collocations: ["downstream consumers", "downstream effects", "break things downstream"],
    slot: "Explaining that a small local change is not locally contained.",
    antiPattern: "Only meaningful when direction is clear. In a cycle, 'downstream' is noise.",
  },
  {
    word: "coupling",
    say: "KUP-ling",
    meaning: "How much two parts must know about each other.",
    collocations: ["tight coupling", "loose coupling", "reduce coupling"],
    slot: "Naming a structural problem without accusing anyone of bad code.",
    antiPattern: "Coupling is not automatically bad — zero coupling means the parts don't work together. The argument is how much.",
  },
  {
    word: "second-order",
    say: "SEK-und-OR-der",
    meaning: "The effect of the effect — what happens once people react.",
    collocations: ["second-order effect", "second-order consequences", "think second-order"],
    slot: "The strongest thing you can say in a design review that nobody else has said.",
    antiPattern: "Not merely 'a later effect'. Second-order specifically means the response to the first effect.",
  },
  {
    word: "brittle",
    say: "BRIT-ul",
    meaning: "Works until conditions shift slightly, then fails completely.",
    collocations: ["brittle system", "brittle assumption", "brittle in production"],
    slot: "Describing something that passes every test and still worries you.",
    antiPattern: "Brittle is not 'fragile under load'. Brittle things work perfectly right up to the break.",
  },
  {
    word: "robust",
    say: "roh-BUST",
    meaning: "Holding up under conditions it was not specifically designed for.",
    collocations: ["robust to noise", "robust under load", "a robust finding"],
    slot: "Praising a design for what it survives rather than what it does.",
    antiPattern: "Robust always takes a 'to what'. Robust in general is a compliment with no content.",
  },
  {
    word: "bottleneck",
    say: "BOT-ul-nek",
    meaning: "The one constraint setting the pace of everything else.",
    collocations: ["the bottleneck is", "relieve the bottleneck", "move the bottleneck"],
    slot: "Redirecting an optimisation effort that is improving the wrong stage.",
    antiPattern: "There is normally exactly one bottleneck at a time. A list of four bottlenecks is a list of complaints.",
  },
  {
    word: "throughput",
    say: "THROO-put",
    meaning: "How much gets through per unit of time.",
    collocations: ["increase throughput", "throughput versus latency", "sustained throughput"],
    slot: "Separating 'how fast is one thing' from 'how much in total'.",
    antiPattern: "Not the same as speed. Doubling throughput while doubling latency is a real and common trade.",
  },
  {
    word: "latent",
    say: "LAY-tunt",
    meaning: "Present but not yet showing.",
    collocations: ["latent defect", "latent demand", "latent capacity"],
    slot: "Naming a problem that exists now and will surface later.",
    antiPattern: "Latent means already there. A risk that might arise is not latent, it is potential.",
  },
  {
    word: "deterministic",
    say: "di-ter-min-IS-tik",
    meaning: "Same input, same output, every time.",
    collocations: ["deterministic build", "deterministic ordering", "non-deterministic failure"],
    slot: "Explaining why a bug that appears once a week is a different class of problem.",
    antiPattern: "Deterministic does not mean predictable to you. A chaotic system can be perfectly deterministic.",
  },
  {
    word: "stochastic",
    say: "stuh-KAS-tik",
    meaning: "Governed by chance in a way you can describe statistically.",
    collocations: ["stochastic process", "stochastic sampling", "stochastic rather than random"],
    slot: "Distinguishing noise you can model from noise you cannot.",
    antiPattern: "Not a fancy word for random. Stochastic implies the randomness has a known distribution.",
  },

  // ── Judgement, evidence, argument ─────────────────────────────────────────
  {
    word: "consensus",
    say: "kun-SEN-sus",
    meaning: "Genuine agreement across a group, arrived at rather than assumed.",
    collocations: ["reach consensus", "build consensus", "rough consensus", "no consensus yet"],
    slot: "Ending a meeting honestly: a decision is not the same as consensus.",
    antiPattern: "Not unanimity, not a vote, and not the absence of objection. Silence is silence.",
  },
  {
    word: "nuance",
    say: "NEW-ahnss",
    meaning: "A small distinction that changes the meaning.",
    collocations: ["miss the nuance", "there is nuance here", "a nuanced position"],
    slot: "Rescuing a point being rounded off to the nearest slogan.",
    antiPattern: "Not 'detail' or 'complexity'. A nuance must alter the conclusion or it is just more information.",
  },
  {
    word: "hindsight",
    say: "HYND-syt",
    meaning: "Understanding available only after the fact.",
    collocations: ["in hindsight", "with the benefit of hindsight", "hindsight bias"],
    slot: "Admitting an error without theatrics.",
    antiPattern: "It should introduce something you genuinely could not have known — otherwise it is an excuse in a nicer coat.",
  },
  {
    word: "in-house",
    say: "IN-howss",
    meaning: "Done by your own people rather than bought or contracted out.",
    collocations: ["keep it in-house", "in-house counsel", "built in-house"],
    slot: "Build-versus-buy conversations, and anything involving an agency.",
    antiPattern: "It takes an object — something is kept in-house. 'We are in-house' is not a sentence.",
  },
  {
    word: "arbitrary",
    say: "AR-bi-tra-ree",
    meaning: "Chosen without a principled reason behind it.",
    collocations: ["an arbitrary cutoff", "somewhat arbitrary", "arbitrary but consistent"],
    slot: "Naming a threshold as convention so people stop defending it as physics.",
    antiPattern: "Not the same as wrong. An arbitrary line can be worth holding; it could just have been drawn elsewhere.",
  },
  {
    word: "converge",
    say: "kun-VERJ",
    meaning: "To move toward the same position from different starting points.",
    collocations: ["converge on a decision", "converge quickly", "fail to converge"],
    slot: "Steering a long discussion toward an outcome without cutting anyone off.",
    antiPattern: "Converging because time ran out is not convergence. If the pressure was the clock, say the clock.",
  },
  {
    word: "concede",
    say: "kun-SEED",
    meaning: "To grant a point to the other side.",
    collocations: ["concede the point", "readily concede", "I'll concede that"],
    slot: "First thirty seconds of any disagreement you intend to win.",
    antiPattern: "Conceding a trivial point to look fair while dodging the real one is transparent.",
  },
  {
    word: "categorical",
    say: "kat-uh-GOR-i-kul",
    meaning: "Admitting no exceptions; absolute.",
    collocations: ["a categorical claim", "categorically deny", "not categorical"],
    slot: "Marking the difference between 'always' and 'usually' before someone else does.",
    antiPattern: "Not 'emphatic'. A categorical statement has no exceptions, not extra volume.",
  },
  {
    word: "tenuous",
    say: "TEN-yoo-us",
    meaning: "Thin; weakly supported.",
    collocations: ["a tenuous link", "tenuous evidence", "tenuous at best"],
    slot: "Pre-empting the weakest part of your own argument.",
    antiPattern: "It describes the connection, not the person, and it stops meaning anything if you use it for everything you dislike.",
  },
  {
    word: "corroborate",
    say: "kuh-ROB-uh-rayt",
    meaning: "To support a claim with independent evidence.",
    collocations: ["corroborate the finding", "independently corroborated", "nothing corroborates it"],
    slot: "Distinguishing a number you verified from a number you were told.",
    antiPattern: "It must be independent. A second person repeating the first person's number corroborates nothing.",
  },
  {
    word: "warranted",
    say: "WOR-un-tid",
    meaning: "Justified by what is actually there.",
    collocations: ["not warranted by the data", "a warranted conclusion", "warrants a closer look"],
    slot: "Challenging a leap without calling anyone wrong.",
    antiPattern: "Nothing to do with warranty. Note the verb: something warrants attention — it earns it.",
  },
  {
    word: "ostensibly",
    say: "oss-TEN-sib-lee",
    meaning: "On the stated version — with a hint the real reason differs.",
    collocations: ["ostensibly about", "ostensibly neutral", "ostensibly for"],
    slot: "Naming a gap between the stated reason and the real one, politely.",
    antiPattern: "It always carries doubt. If you have none, say 'apparently'.",
  },
  {
    word: "plausible",
    say: "PLAW-zi-bul",
    meaning: "Could be true on the face of it; not yet supported.",
    collocations: ["plausible but unproven", "a plausible mechanism", "barely plausible"],
    slot: "Accepting an explanation provisionally without endorsing it.",
    antiPattern: "Plausible is a low bar, and saying it about your own idea concedes more than you may intend.",
  },
  {
    word: "empirical",
    say: "em-PIRR-i-kul",
    meaning: "Settled by observation rather than by reasoning from principle.",
    collocations: ["an empirical question", "empirical evidence", "empirically"],
    slot: "Ending a theoretical argument that a two-hour experiment would resolve.",
    antiPattern: "'That's an empirical question' is only a good line if you then go and measure it.",
  },
  {
    word: "anomaly",
    say: "uh-NOM-uh-lee",
    meaning: "A result that does not fit the model you are using.",
    collocations: ["an anomaly in the data", "dismiss it as an anomaly", "anomalous"],
    slot: "Refusing to round an inconvenient measurement away.",
    antiPattern: "Calling something an anomaly is a claim that the model is right. Sometimes the anomaly is the finding.",
  },
  {
    word: "confound",
    say: "kun-FOWND",
    meaning: "To be a hidden third factor that muddies a comparison.",
    collocations: ["a confounding variable", "confounded by", "controls for confounders"],
    slot: "Objecting to a before-and-after number where something else also changed.",
    antiPattern: "The everyday sense is 'baffle'. In analysis it is specifically a variable, and the two get mixed up.",
  },
  {
    word: "refute",
    say: "ri-FYOOT",
    meaning: "To disprove, with evidence.",
    collocations: ["refute the claim", "conclusively refuted", "fails to refute"],
    slot: "Reserved for when you actually have the counter-evidence in hand.",
    antiPattern: "Not 'deny' or 'reject'. You can reject a claim you cannot refute, and people notice the difference.",
  },
  {
    word: "vindicate",
    say: "VIN-di-kayt",
    meaning: "To be shown right after being doubted.",
    collocations: ["later vindicated", "vindicate the decision", "vindication"],
    slot: "Describing an outcome that settled an old argument.",
    antiPattern: "Vindication requires there to have been doubt. Being right about something uncontested is not vindication.",
  },
  {
    word: "corollary",
    say: "kuh-ROL-uh-ree",
    meaning: "Something that follows automatically once you accept the main point.",
    collocations: ["a corollary of", "the obvious corollary", "as a corollary"],
    slot: "Extending your own argument one step without appearing to change subject.",
    antiPattern: "A corollary must actually follow. A related thought is not a corollary.",
  },

  // ── Position, power, persuasion ───────────────────────────────────────────
  {
    word: "tenable",
    say: "TEN-uh-bul",
    meaning: "Able to be defended or maintained.",
    collocations: ["not tenable", "a tenable position", "no longer tenable"],
    slot: "Rejecting something firmly while still sounding reasonable.",
    antiPattern: "Formal. In casual conversation 'that doesn't work for us' lands harder.",
  },
  {
    word: "untenable",
    say: "un-TEN-uh-bul",
    meaning: "Impossible to keep defending.",
    collocations: ["an untenable position", "became untenable", "politically untenable"],
    slot: "Describing why someone will have to move, without telling them to.",
    antiPattern: "Untenable is about the position, not the person. It says the ground gave way, not that they were foolish.",
  },
  {
    word: "prevailing",
    say: "pri-VAY-ling",
    meaning: "Currently dominant, without being settled.",
    collocations: ["the prevailing view", "prevailing wisdom", "prevailing rate"],
    slot: "Describing a majority opinion while declining to endorse it.",
    antiPattern: "Prevailing implies contest. If nobody disagrees, it is just the view.",
  },
  {
    word: "orthodoxy",
    say: "OR-thuh-dok-see",
    meaning: "The set of beliefs a field treats as beyond argument.",
    collocations: ["challenge the orthodoxy", "the new orthodoxy", "orthodox approach"],
    slot: "Naming an assumption that is being defended by habit rather than evidence.",
    antiPattern: "Slightly hostile. Calling something orthodoxy says its holders have stopped examining it — be ready to defend that.",
  },
  {
    word: "entrenched",
    say: "en-TRENCHT",
    meaning: "Dug in; costly to shift.",
    collocations: ["deeply entrenched", "entrenched interests", "entrenched process"],
    slot: "Explaining why a good idea is not going to be adopted on its merits.",
    antiPattern: "Entrenched is about cost of change, not about being wrong. Some entrenched things deserve to be.",
  },
  {
    word: "incumbent",
    say: "in-KUM-bunt",
    meaning: "The one already holding the position — and hardest to dislodge.",
    collocations: ["the incumbent vendor", "incumbent advantage", "incumbent on us to"],
    slot: "Competitive analysis, and any conversation about replacing a tool.",
    antiPattern: "Second sense: 'it is incumbent on us' means it is our obligation. Unrelated to the first, and both are common.",
  },
  {
    word: "deference",
    say: "DEF-uh-runss",
    meaning: "Yielding to someone else's judgement because of their standing.",
    collocations: ["out of deference to", "excessive deference", "deference to seniority"],
    slot: "Naming why a room agreed with the most senior person rather than the best argument.",
    antiPattern: "Deference is not respect. You can respect someone and still disagree; deference is where the disagreement stops.",
  },
  {
    word: "dissent",
    say: "di-SENT",
    meaning: "Registered disagreement with a decision that is going ahead anyway.",
    collocations: ["voice dissent", "dissenting view", "dissent on the record"],
    slot: "Disagreeing in a way that is durable rather than obstructive.",
    antiPattern: "Dissent is public and specific. Complaining afterwards is not dissent, it is commentary.",
  },
  {
    word: "capitulate",
    say: "kuh-PIT-yoo-layt",
    meaning: "To stop resisting entirely.",
    collocations: ["capitulate to pressure", "eventually capitulated", "capitulation"],
    slot: "Describing a concession made under pressure rather than persuasion.",
    antiPattern: "Strong and slightly loaded. If someone changed their mind on the evidence, they did not capitulate.",
  },
  {
    word: "repudiate",
    say: "ri-PYOO-dee-ayt",
    meaning: "To reject something publicly, including something you once held.",
    collocations: ["repudiate the claim", "publicly repudiated", "repudiate a commitment"],
    slot: "The formal register for disowning a position, contract, or past statement.",
    antiPattern: "Heavier than 'reject'. You repudiate things you were once associated with; otherwise just disagree.",
  },
  {
    word: "perfunctory",
    say: "per-FUNK-tuh-ree",
    meaning: "Done to satisfy the form, without care.",
    collocations: ["a perfunctory review", "perfunctory approval", "perfunctory nod"],
    slot: "Describing a process that runs but does nothing.",
    antiPattern: "It criticises effort, not skill. A perfunctory review may be perfectly competent and still worthless.",
  },
  {
    word: "substantive",
    say: "SUB-stun-tiv",
    meaning: "About the actual matter rather than the framing or the process.",
    collocations: ["a substantive point", "substantive change", "nothing substantive"],
    slot: "Separating objections about content from objections about wording.",
    antiPattern: "Not 'substantial'. Substantive means it goes to the substance; substantial means it is large.",
  },
  {
    word: "interject",
    say: "in-ter-JEKT",
    meaning: "To insert a remark into someone else's flow.",
    collocations: ["interject briefly", "may I interject", "interjected to say"],
    slot: "Getting into a conversation that is not leaving gaps.",
    antiPattern: "An interjection is short by definition. Interjecting for ninety seconds is interrupting.",
  },
  {
    word: "elicit",
    say: "ih-LISS-it",
    meaning: "To draw out a response that was not being volunteered.",
    collocations: ["elicit a response", "elicit requirements", "designed to elicit"],
    slot: "Describing what a good question does, as distinct from what it asks.",
    antiPattern: "Not 'illicit', which means unlawful. Homophone, opposite register, extremely visible in writing.",
  },
  {
    word: "articulate",
    say: "ar-TIK-yoo-layt (verb) / ar-TIK-yoo-lut (adj)",
    meaning: "To put something vague into words precisely.",
    collocations: ["articulate the tradeoff", "clearly articulated", "struggling to articulate"],
    slot: "Crediting someone for naming a thing the room already felt.",
    antiPattern: "The stress moves with the part of speech. You ar-TIK-yoo-LAYT a point; a person is ar-TIK-yoo-lut.",
  },
  {
    word: "moot",
    say: "MOOT",
    meaning: "No longer worth deciding, because events have overtaken it.",
    collocations: ["the point is moot", "render it moot", "a moot question"],
    slot: "Closing a debate that has been resolved by circumstance rather than argument.",
    antiPattern: "In British legal use, 'moot' means arguable and open — nearly the opposite. Say which you mean if the room is mixed.",
  },
  {
    word: "candid",
    say: "KAN-did",
    meaning: "Frank, especially about something you could have hidden.",
    collocations: ["be candid", "candid about", "a candid assessment"],
    slot: "Signalling that what comes next costs you something to say.",
    antiPattern: "'Let me be candid' followed by a safe opinion is worse than saying nothing.",
  },
  {
    word: "rapport",
    say: "ra-POR",
    meaning: "Easy mutual understanding between people.",
    collocations: ["build rapport", "establish rapport", "instant rapport"],
    slot: "Describing the goal of a first conversation without saying 'networking'.",
    antiPattern: "Final t is silent. And it is mutual by definition — you cannot have rapport one-sidedly.",
  },
  {
    word: "reciprocate",
    say: "ri-SIP-ruh-kayt",
    meaning: "To return in kind.",
    collocations: ["reciprocate the gesture", "expect people to reciprocate", "reciprocity"],
    slot: "Explaining why disclosure has to move first in any real conversation.",
    antiPattern: "It is a response, so it cannot be demanded. Naming that you expect it usually kills it.",
  },
  {
    word: "anecdote",
    say: "AN-ik-doht",
    meaning: "A short true story used to make a point.",
    collocations: ["a quick anecdote", "anecdotal evidence", "the plural of anecdote"],
    slot: "The unit of memorable conversation. One per encounter.",
    antiPattern: "Not 'antidote'. And an anecdote illustrates a claim, it does not prove one.",
  },
  {
    word: "digress",
    say: "dy-GRESS",
    meaning: "To move away from the main subject.",
    collocations: ["if I may digress", "I digress", "a slight digression"],
    slot: "Following an interesting tangent on purpose and naming that you are doing it.",
    antiPattern: "'But I digress' followed by more digression is a tic. Use it to close the detour.",
  },
  {
    word: "superfluous",
    say: "soo-PER-floo-us",
    meaning: "More than is needed; adding nothing.",
    collocations: ["superfluous detail", "rendered superfluous", "largely superfluous"],
    slot: "Cutting your own material before someone stops listening.",
    antiPattern: "Stress the second syllable. It means unnecessary because there is already enough, not merely unhelpful.",
  },

  // ── Commerce, systems at scale ────────────────────────────────────────────
  {
    word: "commodity",
    say: "kuh-MOD-i-tee",
    meaning: "Interchangeable between suppliers, so it competes on price alone.",
    collocations: ["a commodity business", "commoditised", "treat it as a commodity"],
    slot: "Refusing to pay a premium for something undifferentiated.",
    antiPattern: "It is an argument, not a fact. If switching is painful, it is not really a commodity to you.",
  },
  {
    word: "granular",
    say: "GRAN-yuh-ler",
    meaning: "Broken into small enough units to be useful.",
    collocations: ["granular data", "more granular", "granularity"],
    slot: "Asking for detail in a way that specifies the unit of detail.",
    antiPattern: "'More granular' is only a real request if you say granular by what — per project, per hour, per user.",
  },
  {
    word: "attribute",
    say: "uh-TRIB-yoot (verb) / AT-ri-byoot (noun)",
    meaning: "To assign a cost or a result to its source.",
    collocations: ["attribute cost to", "attribution", "hard to attribute"],
    slot: "Explaining why a summary number is not actionable.",
    antiPattern: "Stress moves with the part of speech. You uh-TRIB-yoot the spend; the AT-ri-byoot is a property.",
  },
  {
    word: "aggregate",
    say: "AG-ri-gut (noun) / AG-ri-gayt (verb)",
    meaning: "The total, with the individual cases no longer visible.",
    collocations: ["in aggregate", "aggregate demand", "aggregate the results"],
    slot: "Warning that a healthy total is hiding an unhealthy distribution.",
    antiPattern: "'In aggregate we're fine' is the single most common way a real problem gets buried.",
  },
  {
    word: "proxy",
    say: "PROK-see",
    meaning: "A thing you can measure standing in for the thing you care about.",
    collocations: ["a proxy for", "an imperfect proxy", "proxy metric"],
    slot: "Admitting the limits of your own dashboard before someone else finds them.",
    antiPattern: "Every proxy eventually gets optimised for directly, at which point it stops being a proxy.",
  },
  {
    word: "externality",
    say: "eks-ter-NAL-i-tee",
    meaning: "A cost or benefit landing on someone outside the transaction.",
    collocations: ["negative externality", "externalise the cost", "priced externality"],
    slot: "Naming who pays for a decision that looked free to the people making it.",
    antiPattern: "The defining feature is that it falls *outside*. A cost you bear yourself is not an externality.",
  },
  {
    word: "amortise",
    say: "AM-or-tyze",
    meaning: "To spread a large one-off cost across the period it benefits.",
    collocations: ["amortise the cost", "amortised over", "amortisation"],
    slot: "Defending an expensive investment against a single-quarter comparison.",
    antiPattern: "Amortising a cost does not reduce it. Used as rhetoric it is a way of making a big number look small.",
  },
  {
    word: "consolidate",
    say: "kun-SOL-i-dayt",
    meaning: "To merge several things into one, usually for leverage or cost.",
    collocations: ["consolidate vendors", "industry consolidation", "consolidate the estate"],
    slot: "Proposing a reduction in surface area rather than a new capability.",
    antiPattern: "Consolidation almost always trades resilience for efficiency. Say so before someone else does.",
  },
  {
    word: "obsolete",
    say: "OB-suh-leet",
    meaning: "Superseded — still functional, no longer the thing anyone would choose.",
    collocations: ["render obsolete", "functionally obsolete", "obsolescence"],
    slot: "Describing something that works fine and should still be replaced.",
    antiPattern: "Obsolete is not broken. Conflating the two is how working systems get thrown away early.",
  },
  {
    word: "supplant",
    say: "suh-PLANT",
    meaning: "To take the place of, and displace what was there.",
    collocations: ["supplant the incumbent", "gradually supplanted", "supplanted by"],
    slot: "Describing a replacement that was not invited.",
    antiPattern: "Supplanting implies displacement. If both survive, one did not supplant the other.",
  },
  {
    word: "interoperable",
    say: "in-ter-OP-uh-ruh-bul",
    meaning: "Able to work with other systems without special arrangements.",
    collocations: ["interoperable standard", "fully interoperable", "interoperability"],
    slot: "Arguing for a standard over a bespoke integration.",
    antiPattern: "Interoperable means without special-casing. Two systems joined by an adapter you maintain are not interoperable.",
  },
  {
    word: "friction",
    say: "FRIK-shun",
    meaning: "Effort in a process that produces nothing.",
    collocations: ["reduce friction", "friction cost", "frictionless"],
    slot: "Naming why an available option is not being used.",
    antiPattern: "Some friction is load-bearing — a confirmation step is friction on purpose. Removing all of it is not a goal.",
  },
  {
    word: "diminishing returns",
    say: "di-MIN-ish-ing ri-TURNS",
    meaning: "Each additional unit of effort buying less than the one before.",
    collocations: ["hit diminishing returns", "sharply diminishing", "past the point of"],
    slot: "Stopping work that is still producing improvement but no longer worth it.",
    antiPattern: "Diminishing is not zero. Saying it about work with real gains left is how good projects get cut early.",
  },
  {
    word: "plateau",
    say: "PLAT-oh",
    meaning: "A flat stretch after a rise, with no obvious next step up.",
    collocations: ["hit a plateau", "plateaued", "a long plateau"],
    slot: "Describing progress that has stopped without anything going wrong.",
    antiPattern: "A plateau implies the previous approach is exhausted. Slower progress is not yet a plateau.",
  },
  {
    word: "inflection point",
    say: "in-FLEK-shun point",
    meaning: "Where the direction of change itself changes.",
    collocations: ["at an inflection point", "a genuine inflection", "past the inflection"],
    slot: "Marking a shift in rate, not merely a large event.",
    antiPattern: "Badly overused. It is about the curve bending, not about something big happening.",
  },
  {
    word: "path dependence",
    say: "path di-PEN-dunss",
    meaning: "Where you can go now is limited by the route you took here.",
    collocations: ["path-dependent", "path dependence in the design", "locked in by history"],
    slot: "Explaining why an obviously better design cannot simply be adopted.",
    antiPattern: "It is an explanation, not an excuse. Path dependence describes the cost of change; it does not remove the option.",
  },
  {
    word: "canonical",
    say: "kuh-NON-i-kul",
    meaning: "The one official version everything else refers to.",
    collocations: ["the canonical source", "canonical form", "canonicalise"],
    slot: "Settling which of four copies of a document or record is the real one.",
    antiPattern: "Canonical means authoritative by designation, not merely most used. Someone has to declare it.",
  },
  {
    word: "ubiquitous",
    say: "yoo-BIK-wi-tus",
    meaning: "Present everywhere, to the point of being unremarkable.",
    collocations: ["now ubiquitous", "ubiquitous computing", "near-ubiquitous"],
    slot: "Describing a technology that has stopped being a decision.",
    antiPattern: "Ubiquitous is about being taken for granted, not about being popular. Popular things are still noticed.",
  },
  {
    word: "obviate",
    say: "OB-vee-ayt",
    meaning: "To remove the need for something entirely.",
    collocations: ["obviate the need for", "obviates the problem"],
    slot: "The strongest kind of solution: not solving the problem, deleting it.",
    antiPattern: "Not 'avoid' or 'make obvious'. Obviating means the requirement no longer exists.",
  },
  {
    word: "heuristic",
    say: "hyoo-RIS-tik",
    meaning: "A rule that usually works and is not guaranteed to.",
    collocations: ["a useful heuristic", "rely on heuristics", "heuristically"],
    slot: "Offering a rule of thumb while marking that it is one.",
    antiPattern: "A heuristic that you never check is just a belief. The word carries an obligation to notice when it fails.",
  },
  {
    word: "benchmark",
    say: "BENCH-mark",
    meaning: "A fixed reference you measure against repeatedly.",
    collocations: ["benchmark against", "an industry benchmark", "benchmark suite"],
    slot: "Insisting that a comparison have a fixed baseline.",
    antiPattern: "A benchmark stops being one the moment you start optimising for it specifically.",
  },
  {
    word: "awry",
    say: "uh-RYE",
    meaning: "Off course; not as planned.",
    collocations: ["go awry", "something went awry", "plans awry"],
    slot: "A lighter, less alarming way to say something failed.",
    antiPattern: "Rhymes with 'reply', not 'sorry'. Almost always paired with 'go'.",
  },
  {
    word: "epitome",
    say: "ih-PIT-uh-mee",
    meaning: "The purest example of a thing.",
    collocations: ["the epitome of", "epitomise"],
    slot: "A compact compliment or insult, depending what follows 'of'.",
    antiPattern: "Four syllables ending in 'ee'. And it means perfect example, not peak — that is 'pinnacle'.",
  },
  {
    word: "hyperbole",
    say: "hy-PER-buh-lee",
    meaning: "Deliberate exaggeration, not meant literally.",
    collocations: ["that's hyperbole", "without hyperbole", "prone to hyperbole"],
    slot: "Calling out an inflated claim without calling it a lie.",
    antiPattern: "Four syllables; it does not rhyme with 'superbowl'. The adjective shifts: hy-per-BOL-ik.",
  },
  {
    word: "banal",
    say: "buh-NAHL",
    meaning: "Dull through being obvious and repeated.",
    collocations: ["banal observation", "banal small talk", "banality"],
    slot: "Describing conversation that is inoffensive and empty.",
    antiPattern: "Not 'BAY-nul'. A banal statement is usually true — that is the problem with it.",
  },
  {
    word: "caveat",
    say: "KAV-ee-at",
    meaning: "A warning or condition attached to something.",
    collocations: ["with one caveat", "the usual caveats", "caveat that"],
    slot: "Agreeing while putting your condition on the record.",
    antiPattern: "A caveat qualifies a claim, it does not withdraw it. If yours cancels your point, you had no point.",
  },
  {
    word: "paradigm",
    say: "PARA-dyme",
    meaning: "The whole framework a field currently thinks inside.",
    collocations: ["a paradigm shift", "the dominant paradigm", "outside the paradigm"],
    slot: "Rare, and stronger for being rare — a genuine change of framework.",
    antiPattern: "Silent g here, audible in paradigmatic. And almost nothing is a paradigm shift; most things are a good release.",
  },
];

export const GLOSSARY: ReadonlyMap<string, Gloss> = new Map(ENTRIES.map((g) => [g.word, g]));

export const ALL_WORDS: readonly string[] = ENTRIES.map((g) => g.word);

export function gloss(word: string): Gloss | undefined {
  return GLOSSARY.get(word);
}
